spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        check_nullability: true
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: CFG_FLYWAY

springdoc:
  paths-to-exclude:  # 配置不包含在swagger文档中的api
    - /api/test/**
  swagger-ui:
    enabled: false  # 开启/禁止swagger
    path: /swagger-ui.html  # swagger页面
  api-docs:
    enabled: false # 开启/禁止api-docs
    path: /api-docs # api的json文档
  use-management-port: false
