spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: CFG_FLYWAY
