server:
  port: 13500

spring:
  application:
    name: OHMMX-STEAM
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/database?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password
    validationQuery: SELECT 1

steam:
  proxy:
    enable: false
    protocal: socks5
    host: 127.0.0.1
    port: 8000
  apikey: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  id64: 77777777777777777
