server:
  port: 13500

spring:
  application:
    name: OHMMX-STEAM
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/database?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password
    validationQuery: SELECT 1

springdoc:
  packages-to-scan: # 需要扫描的包,可以配置多个
    - com.ohmmx.steam.community.controller
  paths-to-exclude:  # 配置不包含在swagger文档中的api
    - /api/test/**
  swagger-ui:
    enabled: false  # 开启/禁止swagger
    path: /swagger-ui.html  # swagger页面
  api-docs:
    enabled: false # 开启/禁止api-docs
    path: /api-docs # api的json文档
  use-management-port: false

steam:
  proxy:
    enable: false
    protocal: socks5
    host: 127.0.0.1
    port: 8000
  apikey: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  id64: 77777777777777777
