DELIMITER $$

DROP TRIGGER IF EXISTS TRG_CFG_PARAMETER_DELETE$$
CREATE TRIGGER TRG_CFG_PARAMETER_DELETE
BEFORE UPDATE
ON CFG_PARAMETER
FOR EACH ROW
BEGIN
	INSERT INTO HIS_CFG_PARAMETER
		(ID, NID, BOOLEAN_VALUE, INT_VALUE, DECIMAL_VALUE,
		 LONG_VALUE, STRING_VALUE, RELOADABLE, MODIFY_TIMESTAMP)
	VALUES
		(old.ID, new.ID, old.BOOLEAN_VALUE, old.INT_VALUE, old.DECIMAL_VALUE,
		 old.LONG_VALUE, old.STRING_VALUE, old.RELOADABLE, old.MODIFY_TIMESTAMP);
END$$

DROP TRIGGER IF EXISTS TRG_TSK_QUEUE_DELETE$$
CREATE TRIGGER TRG_TSK_QUEUE_DELETE
BEFORE DELETE
ON TSK_QUEUE
FOR EACH ROW 
BEGIN
	INSERT INTO HIS_TSK_QUEUE
		(TYPE, REFERENCE, STATE, CNT_RETRY, NOT_BEFORE,
		 NOT_AFTER, ST_HIST, ST_PREV, LAST_RUN, TTL,
		 CREATE_TIMESTAMP, MODIFY_TIMESTAMP, LOCKED_BY, TAGS)
	VALUES
		(old.TYPE, old.REFERENCE, old.STATE, old.CNT_RETRY, old.NOT_BEFORE,
		 old.NOT_AFTER, old.ST_HIST, old.ST_PREV, old.LAST_RUN, old.TTL,
		 old.CREATE_TIMESTAMP, old.MODIFY_TIMESTAMP, old.LOCKED_BY, old.TAGS);
END$$

DELIMITER ;
